
version: "3"
services:
  homeassistant:
    container_name: climat_guardian_ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
       - ./config:/config
       - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped
    privileged: true 
    network_mode: host


